version: '3.3'

services:

    mysql:
        image: mysql:latest
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - laravel

    php:
      build:
          context: .
          dockerfile: Dockerfile
          args:
            uid: 1000
      volumes:
          - ./src/:/var/www/laravel/
      networks:
          - laravel
      depends_on:
          - mysql

    nginx:
      image: nginx:latest
      volumes:
          - ./src/:/var/www/laravel/
          - ./build/nginx/default.conf:/etc/nginx/conf.d/default.conf
      ports:
          - 8080:80
      networks:
          - laravel
      depends_on:
          - php
          - mysql

networks:
    laravel:
